jtcheng26/canvas-task-extension

src/pages/Content/modules/components/radial-bar-chart/bar.tsx, src/pages/Content/modules/components/radial-bar-chart/example.tsx, src/pages/Content/modules/components/radial-bar-chart/index.tsx, src/pages/Content/modules/components/radial-bar-chart/types/data.ts, src/pages/Content/modules/components/radial-bar-chart/types/index.ts, src/pages/Content/modules/components/radial-bar-chart/utils/spaceBetween.ts, src/pages/Content/modules/components/radial-bar-chart/utils/strokeRadius.ts, src/pages/Content/modules/components/radial-bar-chart/utils/strokeWidth.ts
Reduce bundle size by 120kb (~40%) by replacing apexcharts with custom svg chart implementation
=> Custom radial bar chart implementation

src/manifest.json, src/pages/Content/index.ts
Add the following match patterns
https://\*.edu/\*
https://\*.au/\*
https://\*.nz/\*
https://\*.ca/\*
https://\*.mx/\*
and minimized performance impact on non-canvas sites
closes #12
=> Accessible on all edu domains and various international hostnames

src/manifest.json
New host urls will be periodically added at users' request.
=> Add .uk to host urls

src/pages/Content/modules/components/ContentLoader.tsx, src/pages/Content/modules/components/TaskChart.tsx, src/pages/Content/modules/components/TaskContainer.tsx, src/pages/Content/modules/components/radial-bar-chart/bar.tsx, src/pages/Content/modules/components/radial-bar-chart/index.tsx
Changed loading indicator when switching between weeks to a less jumpy, sleeker look. Fixed chart so that transition runs properly each time. Closes #16
=> Smaller loading

package-lock.json, src/manifest.json, src/pages/Content/index.ts
Should work in firefox now - still works in chrome. Closes #4
=> Update manifest and index for firefox compatibility

src/pages/Content/modules/components/CourseName.tsx, src/pages/Content/modules/components/Task.tsx, src/pages/Content/modules/components/TaskChart.tsx, src/pages/Content/modules/components/Title.tsx, src/pages/Content/modules/components/radial-bar-chart/bar.tsx, src/pages/Content/modules/components/radial-bar-chart/index.tsx, src/pages/Content/modules/hooks/useAssignments.ts, src/pages/Content/modules/hooks/useAssignments.unit.test.ts
Update styles/colors to work for dark mode extensions. Closes #18
=> Dark mode compatibility

src/pages/Content/index.ts, src/pages/Content/modules/components/ContentLoader.tsx, src/pages/Content/modules/components/TaskContainer.tsx, src/pages/Content/modules/components/TaskList.tsx, src/pages/Content/modules/types/options.ts, src/pages/Options/index.css, src/pages/Options/index.html, src/pages/Options/index.ts
add option to enable/disable headings
=> Due date heading option

.eslintrc, src/pages/Content/index.ts, src/pages/Content/modules/components/Subtitle.tsx, src/pages/Content/modules/components/Task.tsx, src/pages/Content/modules/components/TaskContainer.tsx, src/pages/Content/modules/components/TaskList.tsx, src/pages/Content/modules/constants/index.ts, src/pages/Content/modules/icons/check.tsx, src/pages/Content/modules/icons/index.ts, src/pages/Content/modules/types/assignment.ts, src/pages/Content/modules/types/index.ts, src/pages/Content/modules/types/options.ts, src/pages/Content/modules/types/taskListState.ts, src/pages/Content/modules/utils/assignmentsMarkedAsComplete.ts, src/pages/Content/modules/utils/assignmentsMarkedAsIncomplete.ts, src/pages/Content/modules/utils/finished.ts, src/pages/Content/modules/utils/markAsComplete.ts, src/pages/Content/modules/utils/markAsIncomplete.ts, src/pages/Content/modules/utils/numDone.ts, src/pages/Content/modules/utils/taskComplete.test.ts, src/pages/Content/modules/utils/taskComplete.ts, src/pages/Content/modules/utils/unfinished.ts
Mark assignments as complete, view completed assignments, set completed assignments to incomplete. Closes #35
=> Manually mark assignments as complete

.storybook/styles.css, src/pages/Content/modules/components/arrow-button/ArrowButton.tsx, src/pages/Content/modules/components/course-dropdown/CourseDropdown.tsx, src/pages/Content/modules/components/header/Header.tsx, src/pages/Content/modules/components/task-chart/TaskChart.tsx, src/pages/Content/modules/types/index.ts, src/pages/Content/modules/types/misc.ts
=> SVG arrow icons and less reliance on Instructure css

package-lock.json, package.json, src/manifest.json, src/pages/Background/index.ts, src/pages/Content/index.ts
=> Bugfix 60/align right

src/pages/Content/index.ts, src/pages/Content/modules/components/course-dropdown/CourseDropdown.tsx, src/pages/Content/modules/components/task-chart/TaskChart.tsx, src/pages/Content/modules/components/task-chart/hooks/useChartData.ts, src/pages/Content/modules/components/task-form/TaskForm.tsx, src/pages/Content/modules/components/task-form/components/DatePick.tsx, src/pages/Content/modules/components/task-form/components/TextInput.tsx, src/pages/Content/modules/components/task-form/components/TimePick.tsx, src/pages/Content/modules/constants/defaults/optionsDefaults.json, src/pages/Content/modules/hooks/useAssignments.ts, src/pages/Content/modules/hooks/useCourseColors.ts, src/pages/Content/modules/hooks/useCourses.ts, src/pages/Content/modules/index.tsx, src/pages/Content/modules/types/options.ts, src/pages/Options/index.css, src/pages/Options/index.html, src/pages/Options/index.ts
=> Feature 56/custom task color

package-lock.json, package.json, src/pages/Content/modules/components/content-loader/ContentLoader.tsx, src/pages/Content/modules/components/skeleton/Skeleton.tsx, src/pages/Content/modules/components/task-card/CreateTaskCard.tsx, src/pages/Content/modules/components/task-card/TaskCard.tsx, src/pages/Content/modules/components/task-container/TaskContainer.tsx, src/pages/Content/modules/components/task-form/components/Button.tsx, src/pages/Content/modules/components/task-list/TaskList.tsx, src/pages/Content/modules/components/task-list/components/HeadingGroup.tsx, src/pages/Content/modules/components/task-list/stories/task-list.stories.tsx, src/pages/Options/index.html
=> Feature 70/animations

src/pages/Content/modules/hooks/useAssignments.ts, src/pages/Content/modules/types/assignment.ts
=> Fix certain assignments not showing up

src/pages/Content/modules/components/task-form/TaskForm.tsx, src/pages/Content/modules/hooks/useAssignments.ts, src/pages/Content/modules/hooks/useCourseColors.ts, src/pages/Content/modules/hooks/useCourses.ts, src/pages/Content/modules/hooks/useCourses.unit.test.ts, src/pages/Content/modules/hooks/useNeedsGrading.ts
=> Fix colors not following theme color for courses without custom colors

package-lock.json, package.json, src/manifest-chrome.json, src/manifest-firefox.json, src/pages/Content/modules/components/radial-bar-chart/utils/spaceBetween.ts, src/pages/Content/modules/components/sub-tabs/IconSubTabs1.tsx, src/pages/Content/modules/components/sub-tabs/stories/icon-tabs.stories.tsx, src/pages/Content/modules/components/task-chart/TaskChart.tsx, src/pages/Content/modules/components/task-chart/hooks/useChartData.ts, src/pages/Content/modules/components/task-chart/stories/task-chart.stories.tsx, src/pages/Content/modules/components/task-chart/utils/ringProgress.ts, src/pages/Content/modules/components/task-container/TaskContainer.tsx, src/pages/Content/modules/components/task-form/TaskForm.tsx, src/pages/Content/modules/components/task-list/TaskList.tsx, src/pages/Content/modules/constants/defaults/optionsDefaults.json, src/pages/Content/modules/hooks/useAssignments.ts, src/pages/Content/modules/hooks/useCourseNames.ts, src/pages/Content/modules/hooks/useExperiment.ts, src/pages/Content/modules/hooks/useNeedsGrading.ts, src/pages/Content/modules/types/assignment.ts, src/pages/Content/modules/types/options.ts, src/pages/Options/index.html, src/pages/Options/index.ts
- Return option to show all dashboard courses instead of only active assignments
- Make colored icon tabs an option
- Track total graded/ungraded submissions for instructors
- Additional redundancy for failed requests
- Closes #14
=> Grease work

.github/workflows/node.js.yml, .gitignore, package-lock.json, package.json, src/pages/Content/modules/components/App.tsx, src/pages/Content/modules/components/content-loader/ContentLoader.tsx, src/pages/Content/modules/components/error/ErrorRender.tsx, src/pages/Content/modules/components/task-container/TaskContainer.tsx, src/pages/Content/modules/hooks/useAssignments.ts, src/pages/Content/modules/hooks/useAssignments.unit.test.ts, src/pages/Content/modules/hooks/useCourses.ts, src/pages/Content/modules/hooks/useCourses.unit.test.ts, src/pages/Content/modules/hooks/useExperiment.ts, src/pages/Content/modules/hooks/utils/loadMissingAssignments.ts, src/pages/Content/modules/hooks/utils/loadNeedsGrading.ts, src/pages/Content/modules/tests/data/api/space.ts, src/pages/Content/modules/tests/demo.ts, src/pages/Content/modules/tests/e2e.int.test.tsx, src/pages/Content/modules/tests/load.int.test.ts, src/pages/Content/modules/tests/utils/api.ts, src/pages/Content/modules/tests/utils/generate.ts, src/pages/Content/modules/types/assignment.ts, src/setupTests.ts, utils/styleMock.js
- Use ErrorBoundary to show error message when rendering fails
- Add more error checking and safer code
- Use `testing-library/react` for end-to-end rendering tests
- Better redundancy on partial api responses
=> Better error handling + tests

src/pages/Content/modules/icons/check.tsx
=> feat: add tooltip to check icons

src/pages/Content/content.styles.css, src/pages/Content/entry/detectCanvas.ts
=> Fix dates overlapping course dropdown in list view

ARCHITECTURE.md, CONTRIBUTING.md
=> Create CONTRIBUTING.md, ARCHITECTURE.md

package-lock.json, src/pages/Options/index.css
Closes #128
Super simple fix but not sure if you wanted to keep the height limited in any other way
=> Remove max height limit on dropdown menu

src/pages/Content/entry/gradescope/runInGradescope.ts, src/pages/Content/entry/runInCanvas.ts, src/pages/Content/modules/components/gradescope/utils/migrate.ts, src/pages/Content/modules/components/gradescope/utils/scrape.ts, src/pages/Content/modules/components/gradescope/utils/store.ts, src/pages/Content/modules/hooks/utils/loadGradescope.ts
@ed789d0 Let me know if this resolves #138
=> Move gradescope tasks to local storage
